server:
  port: 8091
  http2:
    enabled: false
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-password: password
    enabled: false
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: json-grpc
          uri: https://localhost:6565
          predicates:
            - Path=/json/**
          filters:
            - JSONToGRPCFilter

# logging:
#   level:
#     '[reactor.netty]': DEBUG
#     '[org.org.springframework.cloud.gateway.filter]': TRACE